# Generated by Django 3.2 on 2023-05-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_title_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Confirmation code'),
            preserve_default=False,
        ),
    ]
